services:
  db:
    hostname: db
    image: pgvector/pgvector:pg17
    restart: always
    ports:
     - 5433:5432
    networks:
      - db
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vectordb
      - POSTGRES_PASSWORD=vectordb
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/Dockerfile
    restart: always
    ports:
     - 8888:80
    networks:
      - db
      - backend
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vectordb
      - POSTGRES_PASSWORD=vectordb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db-fill:
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/fill_db/Dockerfile
    networks:
      - db

volumes:
  db-data:

networks:
  db:
  backend:
